version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: avaliacao-db
    restart: always
    environment:
      - POSTGRES_DB=avaliacao-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"